### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by goelaakash79** [dsckiet/static-website-ui#2]
**Check the code of conduct page, in this repo and integrate it with the main website. Please note that you link to the code of conduct will be in the footer component and at the bottom of about us page.**

**Comment by rhnmht30** [comment]
Successfully added Code of conduct page as well as 404 page to the website. @goelaakash79

**Comment by goelaakash79** [comment]
Please take a look at 404 pages, as discussed.
